name: "CI"

on:
  push:
    branches:
      - master
  pull_request:

env:
  REACT_APP_WEATHER_API_KEY: 92c60dcccea549b8bc0114834222806
  REACT_APP_WEATHER_API_URL: https://api.weatherapi.com/v1

jobs:
  ci:
    name: node-ci
    runs-on: "ubuntu-latest"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "16"

      - name: Install dependencies
        run: yarn install

      - name: Run the linter
        run: yarn lint

      - name: Run the tests
        run: yarn test

      - name: Build
        run: yarn build
